
package it.univaq.disim.mwt.teachify.presentation.webservice.common;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EError", targetNamespace = "http://www.univaq.t/mwt/soa/Teachify.xsd1")
public class Error
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TError faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Error(String message, TError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Error(String message, TError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: t.univaq.mwt.soa.teachify.TError
     */
    public TError getFaultInfo() {
        return faultInfo;
    }

}
